import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
//import styles from '@/styles/Home.module.css'
import * as React from "react";
import Tabs from "@mui/material/Tabs";
import Tab from "@mui/material/Tab";
import Typography from "@mui/material/Typography";
//import Box from "@mui/material/Box";
import { useEffect, useState } from "react";
import Autocomplete from "@mui/material/Autocomplete";
import TextField from "@mui/material/TextField";
import SearchIcon from "@mui/icons-material/Search";
import FlightTakeoffIcon from "@mui/icons-material/FlightTakeoff";
import FlightLandIcon from "@mui/icons-material/FlightLand";
import dynamic from "next/dynamic";
import dayjs, { Dayjs } from "dayjs";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

interface TabPanelProps {
  children?: React.ReactNode;
  index: number;
  value: number;
}

function CustomTabPanel(props: TabPanelProps) {
  const { children, value, index, ...other } = props;
  const DynamicBox = dynamic(() => import("@mui/material/Box"), { ssr: false });

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && (
        <DynamicBox sx={{ p: 3 }}>
          <Typography>{children}</Typography>
        </DynamicBox>
      )}
    </div>
  );
}
function a11yProps(index: number) {
  return {
    id: `simple-tab-${index}`,
    "aria-controls": `simple-tabpanel-${index}`,
  };
}

export default function Home() {
  const [value, setValue] = useState(0);
  const handleChange = (event: React.SyntheticEvent, newValue: number) => {
    setValue(newValue);
  };
  const [airports, setAirports] = useState<any>([]);
  const DynamicAutocomplete = dynamic(
    () => import("@mui/material/Autocomplete"),
    { ssr: false }
  );
  const DynamicBox = dynamic(() => import("@mui/material/Box"), { ssr: false });

  const destination = [
    {
      artwork: "/images/japan.svg",
      country: "Japan",
      capital: "Tokyo",
      amount: 25000,
    },
    {
      artwork: "/images/malay.svg",
      country: "Spain",
      capital: "Madrid",
      amount: 34000,
    },
    {
      artwork: "/images/nepal.svg",
      country: "Nepal",
      capital: "Kath",
      amount: 62000,
    },
    {
      artwork: "/images/korea.svg",
      country: "Korea",
      capital: "Seoul",
      amount: 27000,
    },
    {
      artwork: "/images/australia.svg",
      country: "Autria",
      capital: "Viena",
      amount: 44000,
    },
    {
      artwork: "/images/singapore.svg",
      country: "india",
      capital: "Delhi",
      amount: 41000,
    },
  ];

  async function getAllAirports() {
    try {
      const res = await axios.get(
        "https://airlabs.co/api/v9/airports?api_key=51ced4f1-4f9a-46f6-a405-081ec8c79cc3"
      );
      const getAirports = res.data.response.map((item: any) => item);

      setAirports(getAirports);
    } catch (error) {
      console.error("Error fetching data:", error);
      return {
        props: {
          data: "Error fetching data",
        },
      };
    }
  }
  useEffect(() => {
    getAllAirports();
  }, []);

  return (
    <>
      <Head>
        <title>Book Flight </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@300;400;500;700&family=Poppins:wght@100;400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossOrigin="anonymous"
      ></script>
      <script
        src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossOrigin="anonymous"
      ></script>
      <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossOrigin="anonymous"
      ></script>
      <main>
        <div className="hero-section">
          <nav className="navbar navbar-expand-lg navbar-light">
            <a className="navbar-brand" href="#">
              <img src="/images/Logo.svg" alt="Logo" width="200" height="50" />
            </a>
            <button
              className="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbarNavDropdown"
              aria-controls="navbarNavDropdown"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span className="navbar-toggler-icon"></span>
            </button>
            <div className="collapse navbar-collapse" id="navbarNavDropdown">
              <ul className="navbar-nav">
                <li className="nav-item active">
                  <a className="nav-link" href="#">
                    About
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="#">
                    Login
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="#">
                    Contact Us
                  </a>
                </li>
              </ul>
            </div>
          </nav>
          <div className="home-text">
            <h1>Limited-time offers. Timeless</h1>
            <h1>Adventures</h1>
            <br />
            <h3>Save up to 25%*</h3>

            <button className="book">Book Now</button>
          </div>
        </div>
        <div className="book-flight-container">
          <div className="tab-wrapper">
            <DynamicBox sx={{ width: "100%" }}>
              <DynamicBox sx={{ borderBottom: 1, borderColor: "divider" }}>
                <Tabs
                  value={value}
                  onChange={handleChange}
                  aria-label="basic tabs example"
                  centered
                >
                  <Tab label="Book a flight" {...a11yProps(0)} />
                  <Tab label="manage/check in" {...a11yProps(1)} />
                  <Tab label="flight status" {...a11yProps(2)} />
                </Tabs>
              </DynamicBox>
              <CustomTabPanel value={value} index={0}>
                <DynamicAutocomplete
                  sx={{ marginBottom: "10px" }}
                  options={airports}
                  getOptionLabel={(option: any) =>
                    option.name +
                    " (" +
                    option.iata_code +
                    ", " +
                    option.country_code +
                    ")"
                  }
                  renderInput={(params) => (
                    <TextField
                      {...params}
                      label="From"
                      InputProps={{
                        ...params.InputProps,
                        startAdornment: (
                          <>
                            <FlightTakeoffIcon color="action" />
                            {params.InputProps.startAdornment}
                          </>
                        ),
                      }}
                    />
                  )}
                  renderOption={(props: any, option: any) => (
                    <li {...props}>
                      <span>{option.name}</span>
                      <span style={{ marginLeft: "10px", color: "gray" }}>
                        ({option.iata_code}, {option.country_code})
                      </span>
                    </li>
                  )}
                />

                <DynamicAutocomplete
                  sx={{ marginBottom: "10px" }}
                  options={airports}
                  getOptionLabel={(option: any) =>
                    option.name +
                    " (" +
                    option.iata_code +
                    ", " +
                    option.country_code +
                    ")"
                  }
                  renderInput={(params) => (
                    <TextField
                      {...params}
                      label="To"
                      InputProps={{
                        ...params.InputProps,
                        startAdornment: (
                          <>
                            <FlightLandIcon color="action" />
                            {params.InputProps.startAdornment}
                          </>
                        ),
                      }}
                    />
                  )}
                  renderOption={(props: any, option: any) => (
                    <li {...props}>
                      <span>{option.name}</span>
                      <span style={{ marginLeft: "10px", color: "gray" }}>
                        ({option.iata_code}, {option.country_code})
                      </span>
                    </li>
                  )}
                />
                <div className="flight-wrapper">
                  <button className="show-flight">Show flights</button>
                </div>
              </CustomTabPanel>
              <CustomTabPanel value={value} index={1}>
                <div className="d-flex tab-two">
                  <div className="search-bar">
                    <input
                      type="text"
                      placeholder="Booking Reference"
                      className="bg-trans"
                      value=""
                    />{" "}
                  </div>
                  <div className="search-bar">
                    <input
                      type="text"
                      placeholder="Last Name"
                      className="bg-tran"
                      value=""
                    />{" "}
                  </div>
                </div>

                <br />
                <div className="retrieve-btn-wrapper">
                  <button className="btn-retrieve">Retrieve Booking</button>
                </div>
              </CustomTabPanel>
              <CustomTabPanel value={value} index={2}>
                <div className="d-flex tab-two">
                  <div className="search-bar">
                    <input
                      type="text"
                      placeholder="QR flight Number"
                      className="bg-trans"
                      value=""
                    />{" "}
                  </div>
                  <div className="search-bar">
                    <input
                      type="text"
                      placeholder="Plane Number"
                      className="bg-tran"
                      value=""
                    />{" "}
                  </div>
                </div>

                <br />
                <div className="retrieve-btn-wrapper">
                  <button className="btn-retrieve">Search</button>
                </div>
              </CustomTabPanel>
            </DynamicBox>
          </div>
        </div>

        <div className="container">
          <div className="row">
            <div className="col-12 col-md-6 col-sm-12 gy-4 top-destination-wrapper">
              <h4 className="top-destination-text">Top Destinations</h4>
              <p>
                Dui in in orci fermentum a. Maecenas nunc id ut auctor curabitur
                pellentesque id et tristique. Pellentesque et a nisl aliquam
                eget. Nam velit duis in mauris arcu vivamus amet turpis in. In
                bibendum placerat quam ullamcorper accumsan felis. Velit vitae
                pellentesque sagittis et consequat sit donec. Donec aenean
                vivamus ullamcorper urna aliquet faucibus lacus aliquet.
              </p>
              <button className="book">Discover More</button>
            </div>
            <div className="col-sm-6 col-md  col-12 gy-4">
              <div className="container">
                <div className="row">
                  {destination.map((data) => (
                    <div
                      className="image-card  col-lg-4 col-6 col-md-6"
                      key={data.country}
                    >
                      <img
                        className="travel-img"
                        src={data.artwork}
                        width={155}
                        height={155}
                      />
                      <div className="d-flex justify-content-between card-text">
                        <div>
                          <span className="capital">{data.capital},</span>{" "}
                          <span className="country">{data.country}</span>
                          <p className="price">Rs. {data.amount}</p>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="services-wrapper">
          <div className="container">
            <div className="row">
              <div className="col-12 col-md-6">
                <div className="d-flex ">
                  <div>
                    <p className="itemize">01</p>
                  </div>
                  <div style={{ paddingLeft: "15px" }}>
                    <p className="heading-text">Instant Ticket</p>
                    <p>
                      Eu scelerisque amet amet malesuada id ultrices morbi.
                      Vitae purus mauris hac nisi habitasse donec. Vitae integer
                      massa in blandit.
                    </p>
                  </div>
                </div>
                <div className="d-flex ">
                  <div>
                    <p className="itemize">02</p>
                  </div>
                  <div style={{ paddingLeft: "15px" }}>
                    <p className="heading-text">Worldwide Flight</p>
                    <p>
                      Eu scelerisque amet amet malesuada id ultrices morbi.
                      Vitae purus mauris hac nisi habitasse donec. Vitae integer
                      massa in blandit.
                    </p>
                  </div>
                </div>
                <div className="d-flex ">
                  <div>
                    <p className="itemize">03</p>
                  </div>
                  <div style={{ paddingLeft: "15px" }}>
                    <p className="heading-text">Trusted Booking</p>
                    <p>
                      Eu scelerisque amet amet malesuada id ultrices morbi.
                      Vitae purus mauris hac nisi habitasse donec. Vitae integer
                      massa in blandit.
                    </p>
                  </div>
                </div>
              </div>
              <div className="col-12 col-md-6 col-sm-12">
                <div className="contain">
                  <h4 className="header-text">We offer The Best Services</h4>
                  <button className="btn-basic learn-more">learn more</button>
                </div>
                <img
                  src="/images/illustration.png"
                  width="260"
                  className="mt-5"
                />
              </div>
            </div>
          </div>
        </div>
        <div
          id="carouselExampleIndicators"
          className="carousel slide"
          data-ride="carousel"
        >
          <ol className="carousel-indicators">
            <li
              data-target="#carouselExampleIndicators"
              data-slide-to="0"
              className="active"
            ></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div className="carousel-inner">
            <div className="carousel-item active">
              <img
                className="d-block w-100"
                src="/images/takeoff.jpg"
                alt="First slide"
              />
              <div className="carousel-caption d-none d-md-block">
                <h1>Taking You Further</h1>
              </div>
            </div>
            <div className="carousel-item">
              <img
                className="d-block w-100 "
                src="/images/waiting.jpg"
                alt="Second slide"
              />
              <div className="carousel-caption d-none d-md-block">
                <h1>Let's Go Places Together</h1>
              </div>
            </div>
            <div className="carousel-item">
              <img
                className="d-block w-100"
                src="/images/landing.jpg"
                alt="Third slide"
              />
              <div className="carousel-caption d-none d-md-block">
                <h1>Elevate Your Experience</h1>
              </div>
            </div>
          </div>
          <a
            className="carousel-control-prev"
            href="#carouselExampleIndicators"
            role="button"
            data-slide="prev"
          >
            <span
              className="carousel-control-prev-icon"
              aria-hidden="true"
            ></span>
          </a>
          <a
            className="carousel-control-next"
            href="#carouselExampleIndicators"
            role="button"
            data-slide="next"
          >
            <span
              className="carousel-control-next-icon"
              aria-hidden="true"
            ></span>
          </a>
        </div>
        <div className="subscribe-section">
          <div className="subscribe-box">
            <div className="subscribe-content">
              <h2>Subscribe</h2>
              <h2> to Get Notified About Latest Deals & Offers.</h2>
              <p>
                Eu scelerisque amet amet malesuada id ultrices morbi. Vitae
                purus{" "}
              </p>
              <p>
                mauris hac nisi habitasse donec. Vitae integer massa in blandit.
              </p>
              <div className="search-bar">
                <img src="/images/mail.svg" alt="" />
                <input
                  type="text"
                  placeholder="Email Address"
                  className="bg-trans"
                  value=""
                />{" "}
              </div>{" "}
              <br />
              <button className="btn-subscribe">Subscribe</button>
            </div>
          </div>
        </div>
        <div className="footer">
          <div className="container">
            <div className="row">
              <div className="col foot">
                <a className="nav-link" href="#">
                  Explore
                </a>
              </div>
              <div className="col foot">
                <a className="nav-link" href="#">
                  Bookings
                </a>
              </div>
              <div className="col foot">
                <a className="nav-link" href="#">
                  Ticket
                </a>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
